FROM towhee/towhee-ut
MAINTAINER wxywb <xy.wang@zilliz.com>

RUN pip install towhee \
    && pip install awscli

#RUN yum -y install wget \
#    && wget -O redis.tar.gz "http://download.redis.io/releases/redis-5.0.3.tar.gz" \
#    && tar -xvf redis.tar.gz
